sudo: require
language: default

services:
 - docker

env:
  matrix:
   - DOCKERFILE_TARGET=php
   - DOCKERFILE_TARGET=perl
   - DOCKERFILE_TARGET=python
   - DOCKERFILE_TARGET=ruby
   - DOCKERFILE_TARGET=node-js
   - DOCKERFILE_TARGET=jvm
   - DOCKERFILE_TARGET=go

install:
 - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
 - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
 - sudo apt-get update
 - sudo apt-get install docker-engine

script:
  - sudo docker build -t ${DOCKER_REGISTORY}/${DOCKER_USER}/travis-${DOCKERFILE_TARGET} ${DOCKERFILE_TARGET}
  - sudo docker push ${DOCKER_REGISTORY}/${DOCKER_USER}/travis-${DOCKERFILE_TARGET}

